// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RailwayWebpage.Models.RailwayDbContext;

#nullable disable

namespace RailwayWebpage.Migrations
{
    [DbContext(typeof(RailwayDbContext))]
    [Migration("20231216120008_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RailwayWebpage.Models.Railway.From", b =>
                {
                    b.Property<int>("FId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FId"));

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FId");

                    b.ToTable("froms");
                });

            modelBuilder.Entity("RailwayWebpage.Models.Railway.LoginPage", b =>
                {
                    b.Property<int>("LId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegisterPageRId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LId");

                    b.HasIndex("RegisterPageRId");

                    b.ToTable("LoginPages");
                });

            modelBuilder.Entity("RailwayWebpage.Models.Railway.PassengerDetails", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PId"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("Berth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CMonth")
                        .HasColumnType("integer");

                    b.Property<int>("CYear")
                        .HasColumnType("integer");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CardNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("Cvno")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Phoneno")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PId");

                    b.ToTable("passengerdetailes");
                });

            modelBuilder.Entity("RailwayWebpage.Models.Railway.RegisterPage", b =>
                {
                    b.Property<int>("RId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RId");

                    b.ToTable("RegisterPages");
                });

            modelBuilder.Entity("RailwayWebpage.Models.Railway.TClass", b =>
                {
                    b.Property<int>("CId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CId"));

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrainNameTNId")
                        .HasColumnType("integer");

                    b.HasKey("CId");

                    b.HasIndex("TrainNameTNId");

                    b.ToTable("tclasses");
                });

            modelBuilder.Entity("RailwayWebpage.Models.Railway.To", b =>
                {
                    b.Property<int>("TId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TId"));

                    b.Property<int>("FromFId")
                        .HasColumnType("integer");

                    b.Property<string>("TName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TId");

                    b.HasIndex("FromFId");

                    b.ToTable("tos");
                });

            modelBuilder.Entity("RailwayWebpage.Models.Railway.TPrice", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PId"));

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("TClassCId")
                        .HasColumnType("integer");

                    b.HasKey("PId");

                    b.HasIndex("TClassCId");

                    b.ToTable("tprices");
                });

            modelBuilder.Entity("RailwayWebpage.Models.Railway.TrainName", b =>
                {
                    b.Property<int>("TNId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TNId"));

                    b.Property<string>("TNName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToTId")
                        .HasColumnType("integer");

                    b.HasKey("TNId");

                    b.HasIndex("ToTId");

                    b.ToTable("trainnames");
                });

            modelBuilder.Entity("RailwayWebpage.Models.Railway.LoginPage", b =>
                {
                    b.HasOne("RailwayWebpage.Models.Railway.RegisterPage", "RegisterPage")
                        .WithMany()
                        .HasForeignKey("RegisterPageRId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisterPage");
                });

            modelBuilder.Entity("RailwayWebpage.Models.Railway.TClass", b =>
                {
                    b.HasOne("RailwayWebpage.Models.Railway.TrainName", "TrainName")
                        .WithMany()
                        .HasForeignKey("TrainNameTNId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainName");
                });

            modelBuilder.Entity("RailwayWebpage.Models.Railway.To", b =>
                {
                    b.HasOne("RailwayWebpage.Models.Railway.From", "From")
                        .WithMany()
                        .HasForeignKey("FromFId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");
                });

            modelBuilder.Entity("RailwayWebpage.Models.Railway.TPrice", b =>
                {
                    b.HasOne("RailwayWebpage.Models.Railway.TClass", "TClass")
                        .WithMany()
                        .HasForeignKey("TClassCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TClass");
                });

            modelBuilder.Entity("RailwayWebpage.Models.Railway.TrainName", b =>
                {
                    b.HasOne("RailwayWebpage.Models.Railway.To", "To")
                        .WithMany()
                        .HasForeignKey("ToTId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("To");
                });
#pragma warning restore 612, 618
        }
    }
}
